### ISSUE TITLE
Seq size check N vs size

### ISSUE THREAD

**Issue by jazi007** [tier4/safe_drive#18]
Hello,

There's no safe way to assign data to a message containing a `Seq`

Example: [DiagnosticArray](https://github.com/tier4/safe_drive/blob/main/src/msg/humble/common_interfaces/diagnostic_msgs/msg/diagnostic_array.rs)
```rust
#[repr(C)]
#[derive(Debug)]
pub struct DiagnosticArray {
    pub header: std_msgs::msg::Header,
    pub status: DiagnosticStatusSeq<0>,
}
```

As `status` is an unlimited sized we cannot assign a `DiagnosticStatusSeq<4>` to it for example.
The only way:

```rust
let mut diagnostics = DiagnosticArray::new().unwrap();
let status = DiagnosticStatusSeq::<5>::new(4).unwrap();
unsafe { diagnostics.status = std::mem::transmute(status)};
```

Another remark:
```rust
impl<const N: usize> DiagnosticArraySeq<N> {
    /// Create a sequence of.
    /// `N` represents the maximum number of elements.
    /// If `N` is `0`, the sequence is unlimited.
    pub fn new(size: usize) -> Option<Self> {
        if N != 0 && size >= N {
            // the size exceeds in the maximum number
            return None;
        }
```
isn't `size` check must be `>` instead of `>=`, this gives a strange `API` : `XXSeq::<N>::new(N-1)` ??

Thanks

**Comment by ytakano** [comment]
Thank you.
I will fix it later.

**Comment by jazi007** [comment]
for the safe way my fault it's possible, here's the working solution
```rust
let size = 5;
let mut diag = DiagnosticArray {
    status: DiagnosticStatusSeq::new(size).unwrap(),
    header: Header::new().unwrap(),
}                                                                                                               }; 
```

so only the check `size` vs `N` remains

**Comment by ytakano** [comment]
https://github.com/tier4/safe_drive/commit/07e85500c824fe6a6a75cd4ba431657727473401
Fixing.

**Comment by jazi007** [comment]
Thanks 🙏

**Comment by ytakano** [comment]
Fixed and published.
https://crates.io/crates/safe_drive
