### ISSUE TITLE
[question]: Send not implemented for TakenMsg

### ISSUE THREAD

**Issue by jazi007** [tier4/safe_drive#9]
Hello,

one question, if we try in async code to use several publisher we are facing an issue with `Send/Sync` markers for `TakenMsg`

sample code:

```rust
let logger = Logger::new("async task");
let mut subscriber1 = node.create_subscriber::<std_msgs::msg::String>("topic1", None)?;
let mut subscriber2 = node.create_subscriber::<std_msgs::msg::String>("topic2", None)?;
loop {
         let msg1 = subscriber1.recv().await?;
         let msg2 = subscriber2.recv().await?;
         pr_info!(logger, "{}", msg1.data);
         pr_info!(logger, "{}", msg2.data);
}
```
error:

```bash
has type `TakenMsg<std_msgs::msg::String>` which is not `Send`
```
is this expected ?

**Comment by jazi007** [comment]
FYI: tested locally by implementing Send/Sync for TakenMsg

working fine, if you need a PR for it let me know or correct me if my understanding is wrong

**Comment by ytakano** [comment]
Thank you!
I will check issues and PRs next Tuesday.

**Comment by ytakano** [comment]
Thank you for PR!
